// Code generaTed by fileb0x at "2021-09-26 13:22:58.2719305 +0800 CST m=+1.078499801" from config file "b0x.yaml" DO NOT EDIT.
// modified(2021-09-26 13:21:43.6803927 +0800 CST)
// original path: form-generator/css/parser-example.e1b9068d.css

package gofiles

import (
	"os"
)

// FileCSSParserExampleE1b9068dCSS is "/css/parser-example.e1b9068d.css"
var FileCSSParserExampleE1b9068dCSS = []byte("\x2e\x74\x65\x73\x74\x2d\x66\x6f\x72\x6d\x5b\x64\x61\x74\x61\x2d\x76\x2d\x37\x64\x35\x63\x31\x64\x32\x39\x5d\x7b\x6d\x61\x72\x67\x69\x6e\x3a\x31\x35\x70\x78\x20\x61\x75\x74\x6f\x3b\x77\x69\x64\x74\x68\x3a\x38\x30\x30\x70\x78\x3b\x70\x61\x64\x64\x69\x6e\x67\x3a\x31\x35\x70\x78\x7d")

func init() {

	f, err := FS.OpenFile(CTX, "/css/parser-example.e1b9068d.css", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileCSSParserExampleE1b9068dCSS)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
