// Code generaTed by fileb0x at "2021-09-26 12:40:04.763675 +0800 CST m=+0.194041601" from config file "b0x.yaml" DO NOT EDIT.
// modified(2021-08-20 14:28:44.7573998 +0800 CST)
// original path: form-generator/css/parser-example.69e16e51.css

package gofiles

import (
	"os"
)

// FileCSSParserExample69e16e51CSS is "/css/parser-example.69e16e51.css"
var FileCSSParserExample69e16e51CSS = []byte("\x2e\x74\x65\x73\x74\x2d\x66\x6f\x72\x6d\x5b\x64\x61\x74\x61\x2d\x76\x2d\x37\x37\x62\x31\x61\x61\x66\x61\x5d\x7b\x6d\x61\x72\x67\x69\x6e\x3a\x31\x35\x70\x78\x20\x61\x75\x74\x6f\x3b\x77\x69\x64\x74\x68\x3a\x38\x30\x30\x70\x78\x3b\x70\x61\x64\x64\x69\x6e\x67\x3a\x31\x35\x70\x78\x7d")

func init() {

	f, err := FS.OpenFile(CTX, "/css/parser-example.69e16e51.css", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileCSSParserExample69e16e51CSS)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
